### ISSUE TITLE
Gateway cannot access generated services from gateway portal

### ISSUE THREAD

**Issue by sophiaso** [Microsoft/spring-cloud-playground#24]
Caused by generated cloud-gateway.yml has wrong route url for service.

Generated:
```
      routes:
      - id: AzureServiceBusApplication
        uri: lb://AzureServiceBusApplication
        predicates:
        - Path=/AzureServiceBusApplication/**
```

Expected:
```
      routes:
      - id: AzureServiceBusApplication
        uri: lb://azure-service-bus
        predicates:
        - Path=/azure-service-bus/**
```
